### PR TITLE
Update aes to 0.8

### PR DESCRIPTION
**Pull request by nc7s**
Just a regular dependency update.

### CODE REVIEW

**Comment by rrrodzilla** [comment]
Thanks much!

**Comment by rrrodzilla** [comment]
I'll have to see why the build failed when I get home but I'll get it updated then. Thanks again!

**Comment by nc7s** [comment]
Sorry, that's because I missed out the `use aes::Aes256Ctr` line to remove in v3_local :/ do you want me to do another PR?

**Comment by rrrodzilla** [comment]
No worries. I appreciate the PR. you might want to check the tests pass first and I'll take a note to add contribution instructions to help others. Thanks again.

**Pull request merged**
